In [1]:
import requests

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('①内閣支持率は27%.xlsx')

In [4]:
df

,内閣支持率は●%,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,NaN,44470.0,44501.0,44531.0,44562.0,44593.0,44621.0,44652.0,44682.0,44713.0,...,45017.0,45047.0,45078.0,45108.0,45139.0,45170.0,45200.0,45231.0,45261.0,45292
1,支持する,59.0,61.0,65.0,59.0,55.0,61.0,64.0,66.0,60.0,...,52.0,47.0,39.0,40.0,42.0,42.0,33.0,30.0,26.0,27
2,支持しない,25.0,27.0,26.0,30.0,31.0,27.0,27.0,23.0,32.0,...,40.0,44.0,51.0,51.0,50.0,51.0,59.0,62.0,68.0,66
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,※想定

In [9]:
import pandas as pd

# サンプルのデータを作成する
data = {
    'Positive': ['支持する', 59.0, 61.0, 65.0, 59.0, 55.0, 61.0, 64.0, 66.0, 60.0, 58.0, 57.0, 43.0, 42.0, 37.0, 35.0, 39.0, 43.0, 48.0, 52.0, 47.0, 39.0, 40.0, 42.0, 42.0, 33.0, 30.0, 26.0, 27.0, 25.0, 26.0, 26.0, 28.0, 25.0],
    'Negative': ['支持しない', 25.0, 27.0, 26.0, 30.0, 31.0, 27.0, 27.0, 23.0, 32.0, 32.0, 35.0, 49.0, 49.0, 55.0, 57.0, 54.0, 49.0, 44.0, 40.0, 44.0, 51.0, 51.0, 50.0, 51.0, 59.0, 62.0, 68.0, 66.0, 67.0, 66.0, 69.0, 67.0, 67.0],
}

# 'Dates' 列を追加する
data['Dates'] = pd.date_range(start='2021-10-01', periods=len(data['Positive']), freq='M')

# データフレームを作成する
df = pd.DataFrame(data)

# 結果を表示する
print(df)

   Positive Negative      Dates
0      支持する    支持しない 2021-10-31
1      59.0     25.0 2021-11-30
2      61.0     27.0 2021-12-31
3      65.0     26.0 2022-01-31
4      59.0     30.0 2022-02-28
5      55.0     31.0 2022-03-31
6      61.0     27.0 2022-04-30
7      64.0     27.0 2022-05-31
8      66.0     23.0 2022-06-30
9      60.0     32.0 2022-07-31
10     58.0     32.0 2022-08-31
11     57.0     35.0 2022-09-30
12     43.0     49.0 2022-10-31
13     42.0     49.0 2022-11-30
14     37.0     55.0 2022-12-31
15     35.0     57.0 2023-01-31
16     39.0     54.0 2023-02-28
17     43.0     49.0 2023-03-31
18     48.0     44.0 2023-04-30
19     52.0     40.0 2023-05-31
20     47.0     44.0 2023-06-30
21     39.0     51.0 2023-07-31
22     40.0     51.0 2023-08-31
23     42.0     50.0 2023-09-30
24     42.0     51.0 2023-10-31
25     33.0     59.0 2023-11-30
26     30.0     62.0 2023-12-31
27     26.0     68.0 2024-01-31
28     27.0     66.0 2024-02-29
29     25.0     67.0 2024-03-31
30     26.0     66.0 2024-04-30
31     26.0     69.0 2024-05-31
32     28.0     67.0 2024-06-30
33     25.0     67.0 2024-07-31

/var/folders/qy/6hhj9p8x12vd7qr4yhjck7vc0000gn/T/ipykernel_18765/1806187306.py:10: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data['Dates'] = pd.date_range(start='2021-10-01', periods=len(data['Positive']), freq='M')